### ISSUE TITLE
1.0 interface change with plaintext passwords.

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-password#25]
While 1.0 is a major release, and is ok to release a breaking change, there was one unexpected one, which I'd like to discuss

v1.0.0

```ruby
irb(main):001:0> ManageIQ::Password.decrypt("plaintext")
nil
```

v0.3.0

```ruby
irb(main):001:0>  ManageIQ::Password.decrypt("plaintext")
Traceback (most recent call last):
        6: from bin/console:16:in `<main>'
        5: from (irb):3
        4: from (irb):4:in `rescue in irb_binding'
        3: from /Users/jfrey/dev/manageiq-password/lib/manageiq/password.rb:72:in `decrypt'
        2: from /Users/jfrey/dev/manageiq-password/lib/manageiq/password.rb:40:in `decrypt'
        1: from /Users/jfrey/dev/manageiq-password/lib/manageiq/password.rb:43:in `rescue in decrypt'
ManageIQ::Password::PasswordError (can not decrypt v0_key encrypted string)
```

The reason is because a "plaintext" string was actually considered a v0 encrypted string, because v0 was from before we introduced the v1/v2 prefix.  However, in 1.0.0 we dropped support for v0 and v1 encrypted strings.

There are 2 paths forward:
- Leave it as is and let plaintext return nil
- Change it so that plaintext strings raise a ManageIQ::Password::PasswordError

I prefer the second one.  _Technically_ it's a breaking change, but I don't think anybody relied on this broken behavior because we already have the `try_decrypt` interface for when you know you might both plaintext vs encrypted, and the regular `decrypt` is expected to blow up on _actual_ plaintext strings (as opposed to v0 encrypted strings)

**Comment by Fryguy** [comment]
Created https://github.com/ManageIQ/manageiq-password/pull/26 to show what the exception style would look like.

**Comment by agrare** [comment]
Yeah I think raising an exception if it isn't a V2 key is right and no need for another major release
